version: '3'
services:
  node:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=merman.whatdandoes.info
      - LETSENCRYPT_HOST=merman.whatdandoes.info
      - LETSENCRYPT_EMAIL=daniel@whatdandoes.info
    volumes:
      - .:/home/node
      - /home/node/node_modules
    depends_on:
      - merman_mongo
  # Note to future self: containers keep tripping over one another
  # This mongo composition is named merman_mongo which seems to keep it
  # from bothering with other mongo instances
  merman_mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - merman_data:/data/db
volumes:
  merman_data:
networks:
  default:
    external:
      name: nginx-proxy
